language: fr
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
  case_sensitive: false
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: DucklingEntityExtractor
  url: http://duckling:8000
  dimensions: ["time", "number", "phone-number"]
  locale: "fr_FR"
  timezone: "Europe/Paris"
  timeout: 3
- name: EntitySynonymMapper

policies:
- name: RulePolicy
assistant_id: 20250414-103740-all-programming
